export { ClassInfoPage } from './ClassInfoPage'
export { ChapterPage } from './cpn-page/ChapterPage/ChapterPage'
export { ResourcePage } from './cpn-page/ResourcePage/ResourcePage'
export { DiscussPage } from './cpn-page/DiscussPage/DiscussPage'
export { ExamPage } from './cpn-page/ExamPage/ExamPage'
export { KnowledgePage } from './cpn-page/KnowledgePage/KnowledgePage'
export { ClassManaPage } from './cpn-page/ClassManaPage/index'
