export { HomePage } from './HomePage/HomePage'
export { LoginPage } from './LoginPages/LoginPage'
export { ClassInfoPage } from './ClassInfoPage/ClassInfoPage'
export { CreateExamPage } from './CreateExamPage/CreateExamPage'
export { StudentClassInfoPage } from './StudentClassInfoPage/StudentClassInfoPage'
